version: '3.9'

services:
  db:
    image: postgres:15
    container_name: weather_db
    restart: always
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: weather_data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: weather_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: weather_data
      DB_USER: weather_user
      DB_PASS: 0000
    command: ["pytest", "-v"]
    volumes:
      - .:/app

volumes:
  pgdata:

